server:
  port: 8081

spring:
  application:
    name: payment-processor

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      security.protocol: SSL
      ssl.truststore.type: PEM
      ssl.truststore.location: ${KAFKA_SSL_TRUSTSTORE_LOCATION:}
      ssl.keystore.type: PEM
      ssl.keystore.location: ${KAFKA_SSL_KEYSTORE_LOCATION:}
    consumer:
      group-id: payment-processor-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

discord:
  webhook:
    url: ${DISCORD_WEBHOOK_URL}

razorpay:
  key-id: ${RAZORPAY_KEY_ID}
  key-secret: ${RAZORPAY_KEY_SECRET}
  webhook-secret: ${RAZORPAY_WEBHOOK_SECRET}